### ISSUE TITLE
don't hardcode any paths

### ISSUE THREAD

**Issue by sg-s** [cosmojg/liu-control#3]
https://github.com/cosmojg/liu-control/blob/c37dc5fa8b5783a40d8d21746c57ab0cc0651a0b/analysis.m#L2

**Comment by cosmojg** [comment]
That's why I threw those at the top of the file, but I agree that it's a very lazy approach. I'm guessing you want me to source an unversioned config file instead?

**Comment by sg-s** [comment]
no, far too complex. just replace with 

```
load ../conductances.mat
```

or if you want to get fancy, use `getpref` and `setpref`
