### ISSUE TITLE
Don't put functions in scripts. Also, you don't need this "parsave" function

### ISSUE THREAD

**Issue by sg-s** [cosmojg/liu-control#4]
https://github.com/cosmojg/liu-control/blob/c37dc5fa8b5783a40d8d21746c57ab0cc0651a0b/analysis.m#L31

Instead, move the save command inside the function you're calling

**Comment by cosmojg** [comment]
What's wrong with having a function in a script? Also, saving data from within liu_stability.m seems messy from a user standpoint.

I guess I could make it toggleable with an optional function input? I agree that it would definitely be less hacky than what I'm currently doing. I'll get to work on it.

**Comment by sg-s** [comment]
> What's wrong with having a function in a script? 

scripts run things and call functions. a function takes an input and spits out an output. having functions in scripts breaks the conceptual separation b/w "things that call functions" and "functions"

the advantage of saving to cache within your function is that the user of your function doesn't have to worry about the cache or saving or anything -- they just call the function, and the function lazily computes stuff if needed.

**Comment by sg-s** [comment]
think of it this way: you want to write functions so that they do the most work, and expose the smallest surface to the user. by having the function handling caching, the user of your function doesn't have to think about caching or worry about saving data -- it just works. also for someone else, who doesn't know what a hash is, etc, this is still accessible to them
